---

- name: run portainer
  become: yes
  docker_container:
    name: portainer
    image: portainer/portainer
    state: started
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
